---
- hosts: all
  tasks:
    - name: Update all packages
      become: yes
      ansible.builtin.package:
        name: '*'
        state: latest
      
    - name: Install desired system packages
      become: yes
      ansible.builtin.package:
        name: 
          - automake
          - bat
          - bzip2
          - colordiff
          - curl
          - gcc
          - git
          - htop
          - jq
          - make
          - mono-complete
          - multitail
          - ncdu
          - telnet
          - whois
          - zsh
          - unzip
          - tmux
          - tmuxinator
          - keychain
      
    - name: Install lsd from their github page
      ansible.builtin.shell: curl -L https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb -o /tmp/lsd_0.23.1_amd64.deb && sudo dpkg -i /tmp/lsd_0.23.1_amd64.deb

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - awscli
          - awscli-local
          - docker-compose
          - poetry
          - requests
          - urllib3
          - yt-dlp

    - name: Ensure fonts directory exist.
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Ensure hack fonts exist
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack nerd font
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    - name: Install oh-my-zsh for my user
      ansible.builtin.include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: cristian
            oh_my_zsh:
              plugins:
                - colored-man-pages
                - command-not-found
                - docker
                - pep8
                - pip
                - sudo
              theme: powerlevel10k/powerlevel10k

    - name: Install powerlevel10k
      ansible.builtin.shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      args:
        creates: $HOME/.oh-my-zsh/custom/themes/powerlevel10k/README.md

    - name: Add custon zsh configuration in a separated file
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        line: ". ~/.zsh_custom_configuration"
        owner: cristian
        regexp: '^\. ~/\.zsh_custom_configuration$'
        state: present
        insertafter: EOF
        create: True
    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/bin"
        state: directory
        mode: '0755'

    - name: Install kubectl
      ansible.builtin.shell: curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o $HOME/bin/kubectl && chmod +x $HOME/bin/kubectl
      args:
        creates: "{{ lookup('env', 'HOME') }}/bin/kubectl"

    - name: Ensure ~/.custom_zsh_configuration exists with the desired content
      ansible.builtin.copy:
        src: files/zsh_custom_configuration
        dest: "{{ lookup('env', 'HOME') }}/.zsh_custom_configuration"
        owner: cristian
        group: cristian
        mode: '0644'
    
    - name: Ensure ~/.tmux.conf exists with the desired content
      ansible.builtin.copy:
        src: files/tmux.conf
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        owner: cristian
        group: cristian
        mode: '0644'

    - name: Ensure ~/.p10k.zsh exists with the desired content
      ansible.builtin.copy:
        src: files/p10k.zsh
        dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
        owner: cristian
        group: cristian
        mode: '0644'